// const projects = [
//   {
//     title: 'Transcendence',
//     image: './images/loginpage-mockup',
//     duration: 'Jan 2024 - Mar 2024',
//     role: 'DevOps & Project Lead',
//     description: 'A cutting-edge real-time online Pong game platform where I served as both DevOps and Backend Developer, while also leading the overall system architecture design. This project showcases advanced features including real-time friend status tracking, comprehensive friend management system, and user preference analysis using ELK Stack. I implemented secure authentication using Google OAuth, demonstrating a blend of modern web technologies and data-driven design principles.',
//     tools: ['Docker', 'Django', 'ELK', 'Prometheus', 'Grafana'],
//     github: 'https://github.com/sejoonkimmm/ft_transcendence',
//     link: 'https://github.com/sejoonkimmm/ft_transcendence',
//   },
//   {
//     title: 'Inception of things',
//     image: './images/iot-mockup',
//     duration: 'Mar 2024 - Apr 2024',
//     role: 'DevOps & Project Lead',
//     description: 'An advanced 42Network project focused on mastering Kubernetes cluster deployment and management. This comprehensive DevOps initiative involved setting up continuous deployment using ArgoCD, which automatically reflects changes from GitHub repositories. The project also encompassed configuring Ingress rules and utilizing tools like Vagrant for Nested-VM environments, significantly enhancing my proficiency in Linux systems and container orchestration.',
//     tools: ['Kubernetes', 'Docker', 'ArgoCD', 'BASH', 'Python'],
//     github: 'https://github.com/sejoonkimmm/Inception-of-things-IoT-',
//     link: 'https://github.com/sejoonkimmm/Inception-of-things-IoT-',
//   },
//   {
//     title: 'Car Instrument Cluster',
//     image: './images/tmdb-mockup',
//     duration: 'July 2024 - Aug 2024',
//     role: 'DevOps Engineer',
//     description: 'As part of the Volkswagen SEA:ME Project, I took on the role of DevOps Engineer to develop an innovative instrument cluster for PiRacer vehicles. I engineered a robust CI/CD pipeline using GitHub Actions, QEMU, and Docker, effectively bridging gaps between different CPU architectures and operating systems. This solution allowed seamless artifact deployment to PiRacers upon code merges, earning praise from project contributors for its simplicity and efficiency compared to traditional QT Framework cross-compilation methods.',
//     tools: ['Github action CI/CD', 'QEMU', 'Agile', 'C++', 'Docker'],
//     github: 'https://github.com/sejoonkimmm/Car-instrument',
//     link: 'https://github.com/sejoonkimmm/Car-instrument',
//   },
//   {
//     title: 'Autonomous Drive: Lane detection',
//     image: './images/recipeApp-mockup',
//     duration: 'Sep 2024 - Present',
//     role: 'MLOps & Project Lead',
//     description: 'My inaugural project in autonomous driving and MLOps, where I leveraged Jenkins for continuous integration and deployment of machine learning models. I implemented an innovative setup using ngrok to enable Jenkins to detect GitHub code changes in real-time, facilitating continuous model training. This ongoing project represents my foray into the intersection of DevOps practices and machine learning, showcasing my ability to adapt to new technological domains.',
//     tools: ['Python', 'Jenkins', 'Docker'],
//     github: 'https://github.com/SEA-ME-2nd-ADS/Autonomous-Lane-Detection',
//     link: 'https://github.com/SEA-ME-2nd-ADS/Autonomous-Lane-Detection',
//   },
// ];

// export default projects;

const projects = [
  {
    title: 'Transcendence',
    image: './images/loginpage-mockup',
    duration: 'Jan 2024 - Mar 2024',
    role: 'DevOps & Project Lead',
    affiliation: '42Seoul',
    description: 'As part of the 42Seoul curriculum, I led the development of a cutting-edge real-time online Pong game platform. Serving as both DevOps and Backend Developer, I spearheaded the overall system architecture design. This project showcases advanced features including real-time friend status tracking, comprehensive friend management system, and user preference analysis using ELK Stack. I implemented secure authentication using Google OAuth, demonstrating a blend of modern web technologies and data-driven design principles.',
    tools: ['Docker', 'Django', 'ELK', 'Prometheus', 'Grafana'],
    github: 'https://github.com/sejoonkimmm/ft_transcendence',
    link: 'https://github.com/sejoonkimmm/ft_transcendence',
  },
  {
    title: 'Inception of things',
    image: './images/iot-mockup',
    duration: 'Mar 2024 - Apr 2024',
    role: 'DevOps & Project Lead',
    affiliation: '42Seoul',
    description: 'An advanced 42Seoul project focused on mastering Kubernetes cluster deployment and management. This comprehensive DevOps initiative involved setting up continuous deployment using ArgoCD, which automatically reflects changes from GitHub repositories. The project also encompassed configuring Ingress rules and utilizing tools like Vagrant for Nested-VM environments, significantly enhancing my proficiency in Linux systems and container orchestration.',
    tools: ['Kubernetes', 'Docker', 'ArgoCD', 'BASH', 'Python'],
    github: 'https://github.com/sejoonkimmm/Inception-of-things-IoT-',
    link: 'https://github.com/sejoonkimmm/Inception-of-things-IoT-',
  },
  {
    title: 'Car Instrument Cluster',
    image: './images/tmdb-mockup',
    duration: 'July 2024 - Aug 2024',
    role: 'DevOps Engineer',
    affiliation: 'Volkswagen SEA:ME Project',
    description: 'As a key component of the Volkswagen SEA:ME Project, I took on the role of DevOps Engineer to develop an innovative instrument cluster for PiRacer vehicles. I engineered a robust CI/CD pipeline using GitHub Actions, QEMU, and Docker, effectively bridging gaps between different CPU architectures and operating systems. This solution allowed seamless artifact deployment to PiRacers upon code merges, earning praise from project contributors for its simplicity and efficiency compared to traditional QT Framework cross-compilation methods.',
    tools: ['Github action CI/CD', 'QEMU', 'Agile', 'C++', 'Docker'],
    github: 'https://github.com/sejoonkimmm/Car-instrument',
    link: 'https://github.com/sejoonkimmm/Car-instrument',
  },
  {
    title: 'Autonomous Drive: Lane detection',
    image: './images/recipeApp-mockup',
    duration: 'Sep 2024 - Present',
    role: 'MLOps & Project Lead',
    affiliation: 'Volkswagen SEA:ME Project',
    description: 'As part of the Volkswagen SEA:ME Project, this is my inaugural project in autonomous driving and MLOps. I leveraged Jenkins for continuous integration and deployment of machine learning models, implementing an innovative setup using ngrok to enable Jenkins to detect GitHub code changes in real-time, facilitating continuous model training. This ongoing project represents my foray into the intersection of DevOps practices and machine learning, showcasing my ability to adapt to new technological domains within the automotive industry.',
    tools: ['Python', 'Jenkins', 'Docker'],
    github: 'https://github.com/SEA-ME-2nd-ADS/Autonomous-Lane-Detection',
    link: 'https://github.com/SEA-ME-2nd-ADS/Autonomous-Lane-Detection',
  },
];

export default projects;